项目学习/day16/urls.py
from django.contrib import admin
from django.urls import path
from app01 import views
from app01 import account

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('depart/list/', views.depart_list),
    path('depart/add/', views.depart_add),
    path('depart/delete/', views.depart_delete),
    
    #http://127.0.0.1:8000/depart/4(一个整型数字)/edit/
    path('depart/<int:nid>/edit/', views.depart_edit),
    
    path('user/list/',views.user_list),
    path('user/add/', views.user_add),
    path('user/modelform/add/', views.user_modelform_add),
    path('user/<int:nid>/edit/', views.user_edit),
    path('user/<int:nid>/delete/', views.user_delete),
    path('mobile/list/',views.mobile_list),
    path('mobile/add/',views.mobile_add),
    path('mobile/<int:nid>/edit/', views.mobile_edit),
    path('mobile/<int:nid>/delete/', views.mobile_delete),
    path('admin/list/',views.admin_list),
    path('admin/add/',views.admin_add),
    path('admin/<int:nid>/edit/',views.admin_edit),
    path('admin/<int:nid>/delete/',views.admin_delete),
    path('admin/<int:nid>/reset/',views.admin_reset),
    
    path('login/',account.login),
    path('logout/', account.logout),
    
]

项目学习/app01/models.py
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.
class Admin(models.Model):
    """管理员"""
    username = models.CharField(verbose_name="用户名", max_length = 32)
    password = models.CharField(verbose_name="密码",max_length = 64)

class Department(models.Model):
    '''部门表'''
    #id = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name="部门名",max_length=32)
    
    def __str__(self):
        return self.title

class UserInfo(models.Model):
    """员工表"""
    name = models.CharField(verbose_name="姓名", max_length=16)
    password = models.CharField(max_length=64)
    age = models.IntegerField()
    account = models.DecimalField(verbose_name="账户余额",max_digits=10,decimal_places=2, default=0)
    #create_time = models.DateTimeField(verbose_name="入职时间")
    create_time = models.DateField(verbose_name="入职时间")
    
    #on_delete.CASCADE: 级联删除
    #on_delete.SET_NULL: 置空
    department_id = models.ForeignKey(verbose_name="部门",to="Department",to_field="id",null = True, blank = True, on_delete=models.SET_NULL)
    #利用元组来做choice
    gender_choices = (
        (1,"男"),
        (2, "女"),
    )
    gender = models.SmallIntegerField(verbose_name="性别",choices=gender_choices)

class PrettyNum(models.Model):
    """靓号表"""
    mobile = models.CharField(verbose_name="手机号", max_length=11)
    price = models.IntegerField(verbose_name="价格")
    level_choices = (
        (1, "1级别"),
        (2, "2级别"),
        (3, "3级别"),
        (4, "4级别")
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)
    status_choices = (
        (1,"已经占用"),
        (2, "未占用")
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=2)
    
    

项目学习/app01/views.py
from ensurepip import bootstrap
from socket import fromshare
from tokenize import endpats
from xml.dom import ValidationErr
from django.shortcuts import render,redirect
from django.urls import is_valid_path
from matplotlib import widgets
from app01 import models
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe

from app01.utils.pagination import Pagination
from app01.utils.bootstrap import BootStrapModelForm
from app01.utils.encrypt import md5

# Create your views here.
def depart_list(request):
    '''部门列表'''
    # 去数据库获取所有的部门列表
    # [对象，对象，对象]
    queryset = models.Department.objects.all()  
    return render(request, 'depart_list.html', {'queryset': queryset})

def depart_add(request):
    #添加部门
    if request.method == "GET":
        return render(request, "depart_add.html")
    else:
        title = request.POST.get("title")
    
    #保存到数据库
    models.Department.objects.create(title = title)
    
    #重定向回
    return redirect("/depart/list/")

def depart_delete(req):
    '''删除部门'''
    nid = req.GET.get('nid')
    models.Department.objects.filter(id=nid).delete()
    return redirect("/depart/list/")

def depart_edit(req, nid):
    '''修改部门'''
    #根据nid来获取数据
    if req.method == "GET":
        row_object = models.Department.objects.filter(id=nid).first()
    
        return render(req, "depart_edit.html", {"row_object": row_object})
    else:
        title = req.POST.get("title")
        #根据id找到数据中的数据并更新
        models.Department.objects.filter(id=nid).update(title = title)
        return redirect("/depart/list/")

def user_list(request):
    '''用户管理'''
    #获取所有用户列表
    queryset = models.UserInfo.objects.all()
    #for obj in queryset:
        #数据库里所属部门是“department_id_id (第二个的id是自动生成的)”，那么如果用
        #obj.department_id就是自动获取foreign key（django内置）
        
        #print(obj.id,obj.name,obj.get_gender_display(),obj.department_id.title)
    page_obj = Pagination(request, queryset, page_size=2)
    context = {
        "queryset": page_obj.page_queryset,
        "page_string": page_obj.html(),
        }
    
    return render(request, 'user_list.html', context)

def user_add(request):
    if request.method == "GET":
        context = {
            'gender_choices': models.UserInfo.gender_choices,
            'depart_list': models.Department.objects.all()
        }
        return render(request, "user_add.html", context)
    
    user = request.POST.get('user')
    pwd = request.POST.get('password')
    age = request.POST.get('age')
    account = request.POST.get('account')
    ctime = request.POST.get('ctime')
    gender_id = request.POST.get('gender')
    department_id = request.POST.get('department')
    
    models.UserInfo.objects.create(name=user,password=pwd,age=age,account=account,create_time=ctime,gender=gender_id,department_id_id= department_id)

    return redirect("/user/list/")

'''modelform实例'''
from django import forms

class UserModelForm(BootStrapModelForm):
    name = forms.CharField(min_length=3,label="用户名")
    password = forms.CharField(min_length=6,label="密码")
    
    class Meta:
        model = models.UserInfo
        fields = ["name","password","age","account","create_time","gender","department_id"]

def user_modelform_add(request):
    if request.method =="GET":
        
        form = UserModelForm()
        return render(request, "user_modelform_add.html", {"form":form})
    #用POST提交数据,数据校验。
    form = UserModelForm(data=request.POST)
    if form.is_valid():
        print(form.cleaned_data)
        #{'name': '123', 'password': '12345', 'age': 12, 'account': Decimal('0'), 'create_time': datetime.datetime(2001, 12, 20, 0, 0, 
        #tzinfo=backports.zoneinfo.ZoneInfo(key='UTC')), 'gender': 1, 'department_id': <Department: 媒体企划>}
        
        #如果数据合法 保存到数据库
        form.save()
        return redirect("/user/list/")
    else:
        #校验失败：
        return render(request, "user_modelform_add.html", {"form":form})
    
def user_edit(request, nid):
    form = UserModelForm()
    row_object = models.UserInfo.objects.filter(id=nid).first()
    
    # 根据ID去数据库获取要编辑的那一行数据
    if request.method == "GET":
        form = UserModelForm(instance=row_object)
        return render(request, 'user_edit.html', {"form":form})
    
    #将用户新提交的数据更新
    form = UserModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        #默认保存的是用户输入的所有数据, 如果想要在用户输入以外增加一点值
        # form.instance.字段名 = 值
        form.save()
        return redirect('/user/list/')
    
    return render(request, 'user_edit.html', {"form":form})

def user_delete(request,nid):
    models.UserInfo.objects.filter(id=nid).delete()
    return redirect('/user/list/')

def mobile_list(request):
    
    # 方法1
    # q = models.PrettyNum.objects.filter(mobile="18938690936",id=2)
    # print(q)
    
    # 方法2
    # data_dict = {"mobile":"18938690936","id":6}
    # models.PrettyNum.objects.filter(**data_dict)
    # print(data_dict)
    
    
    # models.PrettyNum.object.filter(id=12)           #等于12
    # models.PrettyNum.object.filter(id__gt=12)       #大于12
    # models.PrettyNum.object.filter(id__gte=12)      #大于等于12
    # models.PrettyNum.object.filter(id__lte=12)      #小于等于12
    
        
    data_dict = {}
    search_data = request.GET.get("q","")  # ""为默认值,若搜索为空则把空值返还给前端，然后搜索框里就啥都不显示
    if search_data:
        data_dict["mobile__contains"] = search_data
    res = models.PrettyNum.objects.filter(**data_dict)
    #print(res)
    
    from app01.utils.pagination import Pagination
    # page = int(request.GET.get('page',1))
    # page_size = 10
    # start = (page-1)*page_size
    # end = page*page_size
    queryset = models.PrettyNum.objects.filter(**data_dict).order_by("-level")
    page_object = Pagination(request,queryset,page_size=20)
    
    page_queryset = page_object.page_queryset
    page_string = page_object.html()
    
    context = {
        "queryset":page_queryset, 
        "search_data":search_data, #分完页的数据
        "page_string":page_string   #页码
        }
    
    return render(request, "mobile_list.html", context)

class prettyModelForm(BootStrapModelForm):
    #验证：方式1（字段+正则）
    # mobile = forms.CharField(
    #     label = "手机号",
    #     validators=[RegexValidator(r'^1[3-9]9\d{9}$','手机号格式错误')],
    # )
    
    class Meta:
        model = models.PrettyNum
        fields = ["mobile","price","level","status"]
        #fields = "__all__"
        
            
    # 验证：方式2(钩子方法)
    def clean_mobile(self):
        txt_mobile = self.cleaned_data["mobile"]
        exists = models.PrettyNum.objects.filter(mobile=txt_mobile).exists()
        if exists:
            raise ValidationError("手机号已存在")
        if len(txt_mobile) != 11:
            raise ValidationError("格式错误")
        
        return txt_mobile
      
def mobile_add(request):
    if request.method == "GET":
        form = prettyModelForm()
        return render(request, "pretty_add.html",{"form":form})
    
    form = prettyModelForm(data=request.POST)
    if form.is_valid():
       
        print(form.cleaned_data)
        #如果数据合法 保存到数据库
        form.save()
        return redirect("/mobile/list/")
    else:
        #校验失败：
        return render(request, "pretty_add.html", {"form":form})

class prettyModelFormEdit(forms.ModelForm):
    #mobile = forms.CharField(disabled=True,label="手机号")
    class Meta:
        model = models.PrettyNum
        fields = ["mobile","price","level","status"]
        
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        
        #循环找到所有插件。添加class=form-control
        for name, field in self.fields.items():
            field.widget.attrs = {"class":"form-control","placeholder":field.label}
            
    # 验证：方式2(钩子方法)
    def clean_mobile(self):
        txt_mobile = self.cleaned_data["mobile"]
        
        #当前编辑的哪一行的id
        #id=self.instance.pk   pk:primary key
        exists = models.PrettyNum.objects.exclude(id=self.instance.pk).filter(mobile=txt_mobile).exists()
        if exists:
            raise ValidationError("手机号已存在")
        
        elif len(txt_mobile) != 11:
           raise ValidationError("格式错误")
        
        return txt_mobile
      
def mobile_edit(request, nid):
    '''编辑靓号'''
    row_object = models.PrettyNum.objects.filter(id=nid).first()

    if request.method == "GET":
        form = prettyModelFormEdit(instance=row_object)
        return render(request, "pretty_edit.html", {"form":form})
    
    form = prettyModelFormEdit(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect("/mobile/list/")

    return render(request,"pretty_edit.html", {"form":form})

def mobile_delete(request, nid):
    models.PrettyNum.objects.filter(id=nid).delete()
    return redirect("/mobile/list/") 


def admin_list(request):
    
    # 检查用户是否已经登录，已登录，继续向下走。未登录，跳转回登陆界面。
    # 用户发来请求，获取cookie随机字符串，拿着随机字符串看看session中有没有。
    # request.session["info"]
    info = request.session.get("info")
    if not info:  #若没登陆
        return redirect("/login/" )
    
    data_dict = {}
    search_data = request.GET.get('q',"")
    if search_data:
        data_dict["username__contains"] = search_data
        
    queryset = models.Admin.objects.filter(**data_dict)
    page_object = Pagination(request,queryset)
    context = {
        'queryset':page_object.page_queryset,
        "page_string":page_object.html(),
        "search_data":search_data
        }
    return render(request, 'admin_list.html',context)

class AdminModelForm(BootStrapModelForm):
    
    confirm_password = forms.CharField(
        label="确认密码",
        widget = forms.PasswordInput
        )
    
    class Meta:
        model = models.Admin
        fields = ["username","password","confirm_password"]
        widgets = {
            "password":forms.PasswordInput(render_value=True) #render_value=True:如果密码输入不一致，会在输入框中保留原输入的密码
            }
    

项目学习/app01/templates/admin_list.html
{% extends 'layout.html' %}

{% block content %}
<div>
    <div class="container">
      <div style="margin-bottom: 10px">
        <a class="btn btn-success" href="/admin/add/" target="blank">新建管理员</a>

        <div style="float: right; width: 300px;">
          <form method="get">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="关键字" value="{{search_data}}">
              <span class="input-group-btn">
                <button class="btn btn-default" type="submit">
                  <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
              </span>
            </div>
          </form>
        </div>
      </div> 
      <div class="bs-example" data-example-id="panel-without-body-with-table">
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            管理员列表
          </div>
    
          <!-- Table -->
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>ID</th>
                <th>用户名</th>
                <th>密码</th>
                <th>操作</th>
                <th>重置密码</th>
              </tr>
            </thead>
            <tbody>
            
              {% for obj in queryset %}
            <tr>
                <td>{{obj.id}}</td>
                <td>{{obj.username}}</td>
                <td>******</td>
                <td>
                  <a class="btn btn-primary btn-xs" href = "/admin/{{ obj.id }}/edit/">编辑</a>
                  <a class="btn btn-danger btn-xs" href="/admin/{{ obj.id}}/delete/">删除</a>
                </td>
                <td>
                  <a href="/admin/{{ obj.id }}/reset/">重置密码</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        <ul class="pagination">
          {{ page_string }}
    
        </ul>
      </div>
    </div>
    
  </div>

{% endblock content %}

项目学习/app01/templates/change.html
{% extends 'layout.html' %}
{% block content %}

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">{{ title }}</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label>{{field.label}}</label>
                        {{field}}
                        <span style="color:red;">{{field.errors.0}} </span>   
                    </div>
                {% endfor %}
                
                
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">提交</button>
                  </div>
                </div>
              </form>
        </div>
      </div>
    </div>
{% endblock content %}

项目学习/app01/templates/depart_add.html
{% extends "layout.html" %}

{% block content %}
<div>
  <div class="container">
      <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">新建部门</h3>
          </div>
          <div class="panel-body">
              <form class="form-horizontal" method="post">
                  {% csrf_token %}
                  <div class="form-group">
                    <label class="col-sm-2 control-label">标题</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control" placeholder="标题" name="title">
                    </div>
                  </div>
                  
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-success">保存</button>
                    </div>
                  </div>
                </form>
          </div>
        </div>
  </div>
</div>
{% endblock content %}

项目学习/app01/templates/depart_edit.html
{% extends "layout.html" %}
{% block content%}
<div>
  <div class="container">
      <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">修改部门</h3>
          </div>
          <div class="panel-body">
              <form class="form-horizontal" method="post">
                  {% csrf_token %}
                  <div class="form-group">
                    <label class="col-sm-2 control-label">标题</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control" placeholder="标题" name="title" value = "{{row_object.title}}">
                    </div>
                  </div>
                  
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-success">提交</button>
                    </div>
                  </div>
                </form>
          </div>
        </div>
  </div>
</div>

{% endblock  %}

项目学习/app01/templates/depart_list.html
{% extends 'layout.html' %}

{% block content %}
<div>
  <div class="container">
    <div style="margin-bottom: 10px">
      <a class="btn btn-success" href="/depart/add" target="blank">新建部门</a>
    </div>

    <div class="bs-example" data-example-id="panel-without-body-with-table">
      <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">
          <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
          部门列表
        </div>
  
        <!-- Table -->
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>名称</th>
              <th>操作</th>
            </tr>
          </thead>
          <tbody>
          {% for obj in queryset %}
            <tr>
              <th>{{ obj.id }}</th>
              <td>{{ obj.title }}</td>
              <td>
                <a class="btn btn-primary btn-xs" href = "/depart/{{ obj.id }}/edit/">编辑</a>
                <a class="btn btn-danger btn-xs" href="/depart/delete/?nid={{ obj.id }}">删除</a>
              </td>
              </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock  %}

 

项目学习/app01/templates/error.html
{% extends "layout.html" %}

{% block content %}
    <div class="container">
        <div class="alert alert-danger" role="alert">{{ msg }}</div>
    </div>

{% endblock content %}

项目学习/app01/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
      .navbar{
        border-radius: 0;
      } 
    </style>
    {% block css %}{% endblock css %}
<body>
    <nav class="navbar navbar-default">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">联通用户管理系统</a>
          </div>
      
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><a href="/admin/list">管理员账户</a></li>
              <li><a href="/depart/list">部门管理</a></li>
              <li><a href="/user/list">用户管理</a></li>\
              <li><a href="/mobile/list">靓号管理</a></li>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
              </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <li><a href="#">登录</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" 
                aria-expanded="false">{{ request.session.info.name }} <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">个人资料</a></li>
                  <li><a href="#">我的信息</a></li>
                  <li><a href="/logout/">注销</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                </ul>
              </li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
  </nav>

<div>
    {% block content %} {% endblock %}
</div>


<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
{% block js %}{% endblock js %}
</body>
</html>
 

项目学习/app01/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
  <style>
    .account{
        width: 400px;
        border: 1px solid #dddddd;
        border-radius: 5px;
        box-shadow: 5px 5px 20px #aaa;

        margin-left:auto;
        margin-right: auto;
        margin-top: 100px;
        padding: 20px 40px;
    }
    .account h2 {
        margin-top: 10px;
        text-align: center
    }
  </style>
</head>
<body>
<div class = "account">
    <h2>用户登录</h2>
    <form method="POST" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.username }}
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>密码</label>
            {{ form.password }}
            <span style="color: red;">{{ form.password.errors.0 }}</span>
        </div>
        <input type="submit" value="登录" class="btn btn-primary">
    </form> 

</div>
</body>
</html>

项目学习/app01/templates/mobile_list.html
{% extends 'layout.html' %}

{% block content %}
<div>
    <div class="container">
      <div style="margin-bottom: 10px">
        <a class="btn btn-success" href="/mobile/add/" target="blank">新建靓号</a>

        <div style="float: right; width: 300px;">
          <form method="get">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Search for..." value="{{search_data}}">
              <span class="input-group-btn">
                <button class="btn btn-default" type="submit">
                  <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
              </span>
            </div>
          </form>
        </div>
      </div> 
      <div class="bs-example" data-example-id="panel-without-body-with-table">
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            靓号列表
          </div>
    
          <!-- Table -->
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>ID</th>
                <th>号码</th>
                <th>价格</th>
                <th>级别</th>
                <th>状态</th>
                <th>操作</th>
              </tr>
            </thead>
            <tbody>
            
              {% for obj in queryset %}
            <tr>
                <td>{{obj.id}}</td>
                <td>{{obj.mobile}}</td>
                <td>{{obj.price}}</td>
                <td>{{obj.get_level_display}}</td>
                <td>{{obj.get_status_display}}</td>
                <td>
                  <a class="btn btn-primary btn-xs" href = "/mobile/{{ obj.id }}/edit/">编辑</a>
                  <a class="btn btn-danger btn-xs" href="/mobile/{{ obj.id}}/delete/">删除</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        <nav aria-label="...">
          <ul class="pagination">
            {{ page_string}}
          </ul>
        </nav>
      </div>
    </div>
  </div>

{% endblock content %}

项目学习/app01/templates/pretty_add.html
{% extends 'layout.html' %}
{% block content %}

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">新建靓号</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label>{{field.label}}</label>
                        {{field}}
                        <span style="color:red;">{{field.errors.0}} </span>
                        
                        
                    </div>
                {% endfor %}
                
                
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">提交</button>
                  </div>
                </div>
              </form>
        </div>
      </div>
    </div>
{% endblock content %}


<form method="post">
    {% csrf_token %}
    {% for field in form %}
        {{field.label}}:   {{field}}
    {% endfor %}
    
</form>

项目学习/app01/templates/pretty_edit.html
{% extends "layout.html" %}

{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">编辑靓号</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label>{{field.label}}</label>
                        {{field}}
                        <span style="color:red;">{{field.errors.0}} </span>
                        
                        
                    </div>
                {% endfor %}
                
                
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">提交</button>
                  </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %} 

项目学习/app01/templates/user_modelform_add.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}
{% block content %}

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">新建用户</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label>{{field.label}}</label>
                        {{field}}
                        <span style="color:red;">{{field.errors.0}} </span>
                        
                        
                    </div>
                {% endfor %}
                
                
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">提交</button>
                  </div>
                </div>
              </form>
        </div>
      </div>
    </div>
{% endblock content %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function () {
            $('#id_create_time').datepicker({
                format:"yyyy-mm-dd",
                startDate:"0",
                language:"zh-CN",
                autoclass: true
            });

        })
    </script>
{% endblock %}

<form method="post">
    {% csrf_token %}
    {% for field in form %}
        {{field.label}}:   {{field}}
    {% endfor %}
    
</form>